// <auto-generated />
using System;
using AutoGlass.Infra.Dados.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoGlass.Infra.Dados.Migrations
{
    [DbContext(typeof(AutoGlassContexto))]
    [Migration("20230614210358_add colunas")]
    partial class addcolunas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoGlass.Dominio.Entidades.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CNPJFornecedor")
                        .IsRequired()
                        .HasColumnType("varchar(14)")
                        .HasColumnName("CNPJFornecedor");

                    b.Property<int>("CodigoFornecedor")
                        .HasColumnType("Int")
                        .HasColumnName("CodigoFornecedor");

                    b.Property<int>("CodigoProduto")
                        .HasColumnType("Int")
                        .HasColumnName("CodigoProduto");

                    b.Property<DateTime>("DataFabricacao")
                        .HasColumnType("datetime")
                        .HasColumnName("DataFabricacao");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime")
                        .HasColumnName("DataValidade");

                    b.Property<string>("DescricaoFornecedor")
                        .IsRequired()
                        .HasColumnType("Varchar(1000)")
                        .HasColumnName("DescricaoFornecedor");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasColumnType("Varchar(1000)")
                        .HasColumnName("DescricaoProduto");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("Varchar(500)")
                        .HasColumnName("Nome");

                    b.Property<int>("Situacao")
                        .HasColumnType("Int")
                        .HasColumnName("Situacao");

                    b.HasKey("Id");

                    b.ToTable("Produtos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
